- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
    - name: Build Docker Image
      command: docker build -t cicd .
      args:
        chdir: /var/lib/jenkins/workspace/jenkins-ansible
    - name: tag image
      command: docker tag cicd:latest ramanijadala/cicd:latest
    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: ramanijadala
        password: dckr_pat_Exvv-2BEaMJv1lLvzvo06xelUjY
    - name: Push image
      command: docker push ramanijadala/cicd:latest
    - name: Run container
      command: docker run -d --name mcapp1 -p 8081:8080 ramanijadala/cicd:latest
